# Generated by Django 5.1.3 on 2024-12-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postCode',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='postText',
            field=models.CharField(max_length=1000),
        ),
    ]
