# Generated by Django 5.1.3 on 2024-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_postcode_alter_post_posttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postCode_language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
